# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udn', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decisionparty',
            name='decision',
        ),
        migrations.RemoveField(
            model_name='decisionparty',
            name='party',
        ),
        migrations.AddField(
            model_name='decision',
            name='parties',
            field=models.ManyToManyField(to='udn.Party'),
        ),
        migrations.DeleteModel(
            name='DecisionParty',
        ),
    ]
