# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-07 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udn', '0003_auto_20160702_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decision',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterUniqueTogether(
            name='decision',
            unique_together=set([('date', 'id')]),
        ),
    ]
