# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udn', '0005_auto_20161111_0333'),
    ]

    operations = [
        migrations.RenameField(
            model_name='decision',
            old_name='timestamp',
            new_name='timestamp_add',
        ),
        migrations.RenameField(
            model_name='party',
            old_name='timestamp',
            new_name='timestamp_add',
        ),
        migrations.AddField(
            model_name='decision',
            name='timestamp_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='party',
            name='timestamp_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
