# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-18 00:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udn', '0008_auto_20161117_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decision',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterUniqueTogether(
            name='decision',
            unique_together=set([]),
        ),
    ]
