# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 03:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udn', '0010_auto_20170708_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decision',
            name='updated',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2017, 11, 15, 3, 39, 31, 490818)),
        ),
    ]
