# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 18:18
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sur', '0009_party_notify'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=255, unique=True)),
                ('timestamp_add', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docid', models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('desc', models.CharField(max_length=255)),
                ('ref', models.CharField(max_length=255)),
                ('senate', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('register', models.CharField(max_length=30, null=True, validators=[django.core.validators.RegexValidator(regex='^(T|C|P a Nc|D|E|P|Nc|ERo|Ro|EC|EVC|EXE|EPR|PP|Cm|Sm|Ca|Cad|Az|To|Nt|Co|Ntd|Cmo|Ko|Nco|Ncd|Ncp|ECm|ICm|INS|K|Kv|EVCm|A|Ad|Af|Na|UL|Cdo|Odo|Tdo|Tz|Ncu|Ads|Afs|Ans|Ao|Aos|Aprk|Aprn|Aps|Ars|As|Asz|Azs|Komp|Konf|Kse|Kseo|Kss|Ksz|Na|Nad|Nao|Ncn|Nk|Ntn|Obn|Plen|Plsn|Pst|Rozk|Rs|S|Spr|Sst|Vol|Tm|Tmo|Ntm)$')])),
                ('number', models.PositiveIntegerField(null=True)),
                ('year', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1950)])),
                ('page', models.PositiveIntegerField(null=True)),
                ('posted', models.DateTimeField(db_index=True)),
                ('timestamp_add', models.DateTimeField(auto_now_add=True)),
                ('agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uds.Agenda')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileid', models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('name', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('ocr', models.BooleanField(db_index=True, default=False)),
                ('timestamp_add', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uds.Document')),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('type', models.CharField(db_index=True, max_length=150)),
                ('pubid', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('high', models.BooleanField(db_index=True, default=False)),
                ('subsidiary_region', models.BooleanField(db_index=True, default=False)),
                ('subsidiary_county', models.BooleanField(db_index=True, default=False)),
                ('updated', models.DateTimeField(db_index=True, null=True)),
                ('timestamp_add', models.DateTimeField(auto_now_add=True)),
                ('timestamp_update', models.DateTimeField(auto_now=True)),
                ('reports', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='uds.Publisher')),
            ],
        ),
        migrations.CreateModel(
            name='Retrieved',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_add', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uds.Document')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sur.Party')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uds.Publisher'),
        ),
    ]
