# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 06:27
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('selid', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('high', models.BooleanField(db_index=True, default=False)),
                ('subsidiary_region', models.BooleanField(default=False)),
                ('subsidiary_county', models.BooleanField(default=False)),
                ('timestamp_add', models.DateTimeField(auto_now_add=True)),
                ('timestamp_update', models.DateTimeField(auto_now=True)),
                ('reports', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='uds.Publisher')),
            ],
        ),
    ]
