# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='subsidiary_county',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='subsidiary_region',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
