# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 12:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uds', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            ('CREATE INDEX uds_file_text_idx ON uds_file USING GIN (to_tsvector(\'simple\', text))',),
            ('DROP INDEX uds_file_text_idx',)
        )
    ]
