# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-05 19:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uds', '0002_tempdate_tempdocument'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TempDate',
        ),
        migrations.RemoveField(
            model_name='tempdocument',
            name='publisher',
        ),
        migrations.DeleteModel(
            name='TempDocument',
        ),
    ]
