# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uds', '0002_auto_20170827_0649'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='type',
            field=models.CharField(db_index=True, default='', max_length=150),
            preserve_default=False,
        ),
    ]
