# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uds', '0002_fulltext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='timestamp_add',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='timestamp_add',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
