# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 15:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('uds', '0003_publisher_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='updated',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
