# Generated by Django 2.1.3 on 2018-11-11 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uds', '0003_auto_20171105_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='posted',
            field=models.DateField(db_index=True),
        ),
    ]
