# Generated by Django 2.1.3 on 2018-11-17 07:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uds', '0004_auto_20181111_0445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='docid',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
