# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 16:40
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uds', '0005_agenda_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='selid',
            field=models.IntegerField(default=0, unique=True, validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
    ]
