# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uds', '0006_document_selid'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='page',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
