# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 22:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uds', '0007_document_page'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='selid',
            new_name='docid',
        ),
        migrations.RenameField(
            model_name='publisher',
            old_name='selid',
            new_name='pubid',
        ),
    ]
