# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uds', '0009_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='ocr',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
