# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uds', '0010_file_ocr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='updated',
            field=models.DateTimeField(db_index=True, null=True),
        ),
    ]
