# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 03:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uds', '0011_auto_20170828_1857'),
    ]

    operations = [
        migrations.RunSQL(
            ('CREATE FULLTEXT INDEX text_fulltext_index ON uds_file (text)',),
            ('DROP INDEX text_fulltext_index on uds_file',)
        )
    ]
