# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 17:06
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uds', '0013_auto_20170830_0715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='year',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1950)]),
        ),
    ]
