# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 06:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sur', '0009_party_notify'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('uds', '0015_auto_20170830_1819'),
    ]

    operations = [
        migrations.CreateModel(
            name='Retrieved',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_add', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uds.Document')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sur.Party')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
