# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-26 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessionid', models.CharField(max_length=32)),
                ('assetid', models.CharField(max_length=30)),
                ('data', models.TextField()),
                ('expire', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=1024)),
                ('text', models.TextField()),
                ('expire', models.DateTimeField(null=True)),
            ],
        ),
    ]
