# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2016-07-15 20:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cache', '0002_auto_20160713_0253'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='asset',
            unique_together=set([]),
        ),
    ]
