# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-12 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cache', '0006_auto_20161123_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='assetid',
            field=models.CharField(max_length=150),
        ),
    ]
