# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 05:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cache', '0007_auto_20170812_0822'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Asset',
        ),
        migrations.DeleteModel(
            name='Cache',
        ),
    ]
