#!/bin/bash

remote='legal.pecina.cz'
user="$USER"

./make-static
rsync -avhHzx \
      --exclude '.*' \
      --exclude '*.pyc' \
      --exclude '*~' \
      --exclude '*.po' \
      --exclude 'static/' \
      --exclude 'migrations/' \
      --exclude '__pycache__/' \
      --exclude '#*' \
      --delete \
      legal collect fonts $user@$remote:/var/www/django/legal/
rsync -avhHzx secrets.py $user@$remote:/var/www/django/legal/legal/
ssh $user@$remote 'cd /var/www/django/legal && source activate && pip install -q -r requirements.txt'
ssh $user@$remote 'touch /var/www/django/legal/legal/wsgi.py'
