#!/bin/bash

remote='legal.pecina.cz'
user="legal"
opts='-vrlpthHzx'
files='legal collect fonts activate manage.py requirements.txt'
exc='.* *.pyc *~ *.po static/ migrations/ __pycache__/ #*'
basedir='/var/www/django/legal'

./make-static

excludes=''
for e in $exc; do
    excludes="--exclude $e $excludes"
done

rsync $opts $excludes --delete $files $user@$remote:$basedir/

if [ -e secrets.py ]; then
    rsync $opts secrets.py $user@$remote:$basedir/legal/
fi

ssh $user@$remote 'source activate && pip install -q -r requirements.txt'

ssh $user@$remote 'touch legal/wsgi.py'
