#!/bin/bash

apps='cin cnb common dvt hjp hsp knr lht psj sop szr udn'

for b in $apps; do
    [ $b/static/$b.scss -nt $b/static/$b.css ] && sass --style=compressed $b/static/$b.scss $b/static/$b.css
done
