#!/bin/bash

remote='legal.pecina.cz'

./dosass
./manage.py collectstatic --noinput --ignore='*.scss' --ignore='*.map'
rsync -avhHzx \
      --exclude '.*' \
      --exclude '*.pyc' \
      --exclude '*.pyc' \
      --exclude '*~' \
      --exclude '/aux/' \
      --exclude '/update' \
      --exclude 'static/' \
      --exclude '*.po' \
      --exclude 'migrations/' \
      --exclude '__pycache__/' \
      --exclude '/venv*' \
      --exclude '/repo/' \
      --exclude 'test*' \
      --exclude 'fixtures/*_test*.json' \
      --exclude '/tests/' \
      --exclude '/htmlcov/' \
      --exclude '/dosass' \
      --exclude '*.map' \
      --exclude '*.log' \
      --exclude '*.log.*' \
      --exclude '#*' \
      --exclude '/nohup.out' \
      --delete \
      ./ $remote:/var/www/django/legal/

ssh $remote 'touch /var/www/django/legal/common/wsgi.py'
