#!/bin/bash

remote='legal.pecina.cz'

./make-static
rsync -avhHzx \
      --exclude '.*' \
      --exclude '*.pyc' \
      --exclude '*.pyc' \
      --exclude '*~' \
      --exclude '/aux/' \
      --exclude '/update' \
      --exclude 'static/' \
      --exclude '*.po' \
      --exclude 'migrations/' \
      --exclude '__pycache__/' \
      --exclude '/venv*' \
      --exclude '/repo/' \
      --exclude 'test*' \
      --exclude 'fixtures/*_test*.json' \
      --exclude '/tests/' \
      --exclude '/htmlcov/' \
      --exclude '/dosass' \
      --exclude '*.map' \
      --exclude '*.log' \
      --exclude '*.log.*' \
      --exclude '#*' \
      --exclude '/nohup.out' \
      --exclude '/setup.py' \
      --exclude '/build/' \
      --exclude '/dist/' \
      --exclude '/MANIFEST*' \
      --delete \
      ./ $remote:/var/www/django/legal/

ssh $remote 'cd /var/www/django/legal && source activate && pip install -q -r requirements.txt'
ssh $remote 'touch /var/www/django/legal/common/wsgi.py'
