# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-18 00:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knr', '0006_delete_vatrate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='formula',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='knr.Formula'),
        ),
    ]
