# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 00:32
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sur', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='found',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='party',
            name='party',
            field=models.CharField(db_index=True, max_length=255, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
    ]
