# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2016-07-02 13:49
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udn', '0002_auto_20160701_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='decision',
            name='anonfilename',
            field=models.CharField(blank=True, max_length=255, validators=[django.core.validators.RegexValidator(regex='^[\\w_]+\\.pdf$')]),
        ),
        migrations.AddField(
            model_name='decision',
            name='updated',
            field=models.DateTimeField(db_index=True, null=True),
        ),
    ]
