# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-11 03:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udn', '0004_auto_20161007_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='decision',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='party',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
