# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 13:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('udn', '0007_auto_20161114_1445'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agenda',
            old_name='timestamp',
            new_name='timestamp_add',
        ),
        migrations.RemoveField(
            model_name='party',
            name='timestamp_update',
        ),
    ]
