# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 23:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_preset'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pending',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('args', models.CharField(max_length=255)),
                ('lock', models.CharField(max_length=30)),
                ('timestamp_add', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
