# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_pending'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lock',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('timestamp_add', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
