# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2016-07-06 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpirate',
            name='valid',
            field=models.DateField(db_index=True),
        ),
    ]
