# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2016-07-13 02:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnb', '0003_auto_20160706_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mpistat',
            name='id',
        ),
        migrations.AlterField(
            model_name='fxrate',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='mpistat',
            name='type',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
