# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 09:20
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cnb', '0005_auto_20161117_1358'),
    ]

    operations = [
        migrations.CreateModel(
            name='FXcurrrate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('currency', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator(regex='^[A-Z]{3}$')])),
                ('quantity', models.PositiveIntegerField()),
                ('rate', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('timestamp_add', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='fxrate',
            name='timestamp_add',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mpirate',
            name='timestamp_add',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mpirate',
            name='rate',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterUniqueTogether(
            name='fxcurrrate',
            unique_together=set([('date', 'currency')]),
        ),
    ]
