# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnb', '0006_auto_20170805_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='fxcurrrate',
            name='timestamp_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
