# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-11 03:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dir', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtor',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='discovered',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
