# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 10:49
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dir', '0006_auto_20161117_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtor',
            name='first_name_opt',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='debtor',
            name='name_opt',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)]),
            preserve_default=False,
        ),
    ]
