# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-18 00:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dir', '0007_auto_20161123_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discovered',
            name='desc',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='discovered',
            unique_together=set([]),
        ),
    ]
