# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 08:42
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dir', '0008_auto_20161218_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtor',
            name='year_birth_from',
            field=models.SmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2017)]),
        ),
        migrations.AlterField(
            model_name='debtor',
            name='year_birth_to',
            field=models.SmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2017)]),
        ),
    ]
