# Generated by Django 2.0.6 on 2018-06-14 23:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dir', '0010_debtor_notify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtor',
            name='year_birth_from',
            field=models.SmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2018)]),
        ),
        migrations.AlterField(
            model_name='debtor',
            name='year_birth_to',
            field=models.SmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2018)]),
        ),
    ]
