# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 12:50
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sur', '0002_auto_20160927_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='party',
            field=models.CharField(db_index=True, max_length=80, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
    ]
