# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 23:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sur', '0009_party_notify'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='check_psj',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='party',
            name='check_udn',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='party',
            name='check_uds',
            field=models.BooleanField(default=True),
        ),
    ]
