# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2016-07-13 02:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cache', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='asset',
            unique_together=set([('sessionid', 'assetid')]),
        ),
    ]
