# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-07 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cache', '0004_auto_20160715_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='expire',
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='cache',
            name='expire',
            field=models.DateTimeField(db_index=True, null=True),
        ),
    ]
