# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cache', '0005_auto_20161007_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cache',
            name='url',
            field=models.URLField(db_index=True),
        ),
    ]
