# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2016-07-06 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnb', '0002_auto_20160706_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpirate',
            name='type',
            field=models.CharField(max_length=20, unique_for_date='valid'),
        ),
        migrations.AlterField(
            model_name='mpistat',
            name='type',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
