# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 13:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cnb', '0004_auto_20160713_0253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mpistat',
            old_name='timestamp',
            new_name='timestamp_update',
        ),
    ]
