# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 02:26
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sir', '0014_error'),
    ]

    operations = [
        migrations.CreateModel(
            name='Debtor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(db_index=True, max_length=255)),
                ('court', models.CharField(max_length=20, null=True)),
                ('name', models.CharField(max_length=80, null=True)),
                ('name_opt', models.SmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('first_name', models.CharField(max_length=80, null=True)),
                ('first_name_opt', models.SmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('genid', models.CharField(max_length=9, null=True)),
                ('taxid', models.CharField(max_length=14, null=True)),
                ('birthid', models.CharField(max_length=10, null=True)),
                ('date_birth', models.DateField(null=True)),
                ('year_birth_from', models.SmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2016)])),
                ('year_birth_to', models.SmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2016)])),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Discovered',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(db_index=True, max_length=255)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sir.Vec')),
            ],
        ),
    ]
