# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dir', '0003_auto_20161114_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtor',
            name='timestamp_add',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
