# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-07 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sir', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vec',
            name='bc',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='vec',
            name='datumVyskrtnuti',
            field=models.DateField(db_index=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='osoba',
            unique_together=set([('idOsoby', 'idOsobyPuvodce')]),
        ),
        migrations.AlterUniqueTogether(
            name='vec',
            unique_together=set([('bc', 'rocnik', 'idOsobyPuvodce')]),
        ),
    ]
