# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 16:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sir', '0009_auto_20161012_0403'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vec',
            unique_together=set([('rocnik', 'bc', 'idOsobyPuvodce')]),
        ),
    ]
