# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 02:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sir', '0013_auto_20161025_2137'),
    ]

    operations = [
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('datumZalozeniUdalosti', models.DateTimeField()),
                ('datumZverejneniUdalosti', models.DateTimeField()),
                ('dokumentUrl', models.URLField(null=True)),
                ('spisovaZnacka', models.CharField(max_length=50)),
                ('typUdalosti', models.CharField(max_length=255)),
                ('popisUdalosti', models.CharField(max_length=255)),
                ('oddil', models.CharField(max_length=10, null=True)),
                ('cisloVOddilu', models.IntegerField(null=True)),
                ('poznamkaText', models.TextField(null=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
