# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 23:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sir', '0014_error'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insolvency',
            name='desc',
            field=models.CharField(max_length=255),
        ),
    ]
