# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 01:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sir', '0015_auto_20161027_2356'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('druhRoleVRizeni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sir.DruhRoleVRizeni')),
                ('osoba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sir.Osoba')),
            ],
        ),
        migrations.AddField(
            model_name='vec',
            name='roles',
            field=models.ManyToManyField(to='sir.Role'),
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together=set([('osoba', 'druhRoleVRizeni')]),
        ),
    ]
