# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 23:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sir', '0016_auto_20161029_0106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='osoba',
            name='druhRoleVRizeni',
        ),
        migrations.RemoveField(
            model_name='vec',
            name='osoby',
        ),
    ]
