# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sir', '0025_auto_20161114_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adresa',
            name='timestamp_add',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='insolvency',
            name='timestamp_add',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='osoba',
            name='timestamp_add',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='timestamp_add',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='vec',
            name='timestamp_add',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
