# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sir', '0030_auto_20170812_0822'),
    ]

    operations = [
        migrations.AddField(
            model_name='vec',
            name='refreshed',
            field=models.DateTimeField(db_index=True, null=True),
        ),
    ]
