# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 23:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Preset',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False, unique_for_date='valid')),
                ('value', models.FloatField()),
                ('valid', models.DateField()),
            ],
        ),
    ]
