# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 21:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kos', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Preset',
        ),
    ]
