# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-26 10:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('szr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courtroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('desc', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='szr.Court')),
            ],
        ),
    ]
