# -*- coding: utf-8 -*-
# Generated by Django 1.10rc1 on 2016-08-02 11:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('szr', '0005_auto_20160713_0253'),
        ('psj', '0005_auto_20160731_2210'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='szr.Court')),
            ],
        ),
    ]
