# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-07 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psj', '0006_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courtroom',
            name='desc',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='hearing',
            name='time',
            field=models.DateTimeField(),
        ),
        migrations.AlterUniqueTogether(
            name='hearing',
            unique_together=set([('time', 'id')]),
        ),
    ]
