# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-12 08:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('psj', '0008_auto_20161111_0333'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='timestamp_add',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
