# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psj', '0011_auto_20161114_1441'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courtroom',
            old_name='timestamp',
            new_name='timestamp_add',
        ),
        migrations.RenameField(
            model_name='form',
            old_name='timestamp',
            new_name='timestamp_add',
        ),
        migrations.RenameField(
            model_name='judge',
            old_name='timestamp',
            new_name='timestamp_add',
        ),
        migrations.RemoveField(
            model_name='party',
            name='timestamp_update',
        ),
        migrations.AddField(
            model_name='courtroom',
            name='timestamp_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
