# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-18 00:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psj', '0012_auto_20161117_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hearing',
            name='time',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterUniqueTogether(
            name='hearing',
            unique_together=set([]),
        ),
    ]
