# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psj', '0013_auto_20161218_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hearing',
            name='year',
            field=models.PositiveIntegerField(),
        ),
    ]
