# Generated by Django 2.0.6 on 2018-06-25 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psj', '0015_auto_20170708_0714'),
    ]

    operations = [
        migrations.AddField(
            model_name='hearing',
            name='auxid',
            field=models.IntegerField(default=0),
        ),
    ]
