# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-03 21:57
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mesto', models.CharField(db_index=True, max_length=255, null=True)),
                ('ulice', models.CharField(max_length=255, null=True)),
                ('cisloPopisne', models.CharField(max_length=10, null=True)),
                ('okres', models.CharField(max_length=30, null=True)),
                ('zeme', models.CharField(max_length=255, null=True)),
                ('psc', models.CharField(db_index=True, max_length=5, null=True, validators=[django.core.validators.RegexValidator(regex='\\d{5}')])),
                ('telefon', models.CharField(max_length=30, null=True)),
                ('fax', models.CharField(max_length=30, null=True)),
                ('textAdresy', models.CharField(max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('number', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DruhAdresy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='DruhRoleVRizeni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='DruhStavRizeni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Osoba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idOsobyPuvodce', models.CharField(max_length=20)),
                ('idOsoby', models.CharField(max_length=20)),
                ('nazevOsoby', models.CharField(db_index=True, max_length=255)),
                ('nazevOsobyObchodni', models.CharField(max_length=255, null=True)),
                ('jmeno', models.CharField(db_index=True, max_length=40, null=True)),
                ('titulPred', models.CharField(max_length=50, null=True)),
                ('titulZa', models.CharField(max_length=50, null=True)),
                ('ic', models.CharField(db_index=True, max_length=9, null=True, validators=[django.core.validators.RegexValidator(regex='\\d{1,9}')])),
                ('dic', models.CharField(db_index=True, max_length=14, null=True)),
                ('datumNarozeni', models.DateField(db_index=True, null=True)),
                ('rc', models.CharField(db_index=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(regex='\\d{9,10}')])),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('adresy', models.ManyToManyField(to='sir.Adresa')),
                ('druhRoleVRizeni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sir.DruhRoleVRizeni')),
            ],
        ),
        migrations.CreateModel(
            name='Vec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idOsobyPuvodce', models.CharField(db_index=True, max_length=20)),
                ('senat', models.SmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('bc', models.PositiveIntegerField(db_index=True)),
                ('rocnik', models.PositiveSmallIntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(2008)])),
                ('firstAction', models.DateField(db_index=True)),
                ('lastAction', models.DateField(db_index=True)),
                ('datumVyskrtnuti', models.DateField(null=True)),
                ('link', models.URLField(null=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('druhStavRizeni', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sir.DruhStavRizeni')),
                ('osoby', models.ManyToManyField(to='sir.Osoba')),
            ],
        ),
        migrations.AddField(
            model_name='adresa',
            name='druhAdresy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sir.DruhAdresy'),
        ),
        migrations.AlterUniqueTogether(
            name='vec',
            unique_together=set([('idOsobyPuvodce', 'bc', 'rocnik')]),
        ),
        migrations.AlterUniqueTogether(
            name='osoba',
            unique_together=set([('idOsobyPuvodce', 'idOsoby')]),
        ),
    ]
