# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-07 15:35
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sir', '0002_auto_20161007_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vec',
            name='senat',
            field=models.SmallIntegerField(db_index=True, default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
