# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-09 03:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sir', '0005_auto_20161009_0304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vec',
            name='lastAction',
            field=models.DateField(),
        ),
    ]
