# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-09 03:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sir', '0006_auto_20161009_0310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vec',
            name='lastAction',
            field=models.DateField(db_index=True),
        ),
    ]
