# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-11 00:14
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sir', '0007_auto_20161009_0333'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('datumZalozeniUdalosti', models.DateTimeField()),
                ('datumZverejneniUdalosti', models.DateTimeField()),
                ('dokumentUrl', models.URLField(null=True)),
                ('spisovaZnacka', models.CharField(max_length=50)),
                ('typUdalosti', models.CharField(max_length=255)),
                ('popisUdalosti', models.CharField(max_length=255)),
                ('oddil', models.CharField(max_length=10, null=True)),
                ('cisloVOddilu', models.IntegerField(null=True)),
                ('poznamkaText', models.TextField(null=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='adresa',
            name='mesto',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='adresa',
            name='psc',
            field=models.CharField(max_length=5, null=True, validators=[django.core.validators.RegexValidator(regex='\\d{5}')]),
        ),
        migrations.AlterField(
            model_name='osoba',
            name='datumNarozeni',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='osoba',
            name='dic',
            field=models.CharField(max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='osoba',
            name='ic',
            field=models.CharField(max_length=9, null=True, validators=[django.core.validators.RegexValidator(regex='\\d{1,9}')]),
        ),
        migrations.AlterField(
            model_name='osoba',
            name='jmeno',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='osoba',
            name='nazevOsoby',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='osoba',
            name='rc',
            field=models.CharField(max_length=10, null=True, validators=[django.core.validators.RegexValidator(regex='\\d{9,10}')]),
        ),
        migrations.AlterField(
            model_name='vec',
            name='datumVyskrtnuti',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='vec',
            name='firstAction',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='vec',
            name='idOsobyPuvodce',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='vec',
            name='lastAction',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='vec',
            name='rocnik',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(2008)]),
        ),
        migrations.AlterField(
            model_name='vec',
            name='senat',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
