# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sir', '0021_auto_20161114_1340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='osoba',
            old_name='timestamp',
            new_name='timestamp_add',
        ),
        migrations.AddField(
            model_name='osoba',
            name='timestamp_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
