# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-26 10:39
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('reports', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='szr.Court')),
            ],
        ),
        migrations.CreateModel(
            name='Proceedings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('senate', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('register', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(regex='^(T|C|P a Nc|D|E|P|Nc|ERo|Ro|EC|EVC|EXE|EPR|PP|Cm|Sm|Ca|Cad|Az|To|Nt|Co|Ntd|Cmo|Ko|Nco|Ncd|Ncp|ECm|ICm|INS|K|Kv|EVCm|A|Ad|Af|Na|UL|Cdo|Odo|Tdo|Tz|Ncu|Ads|Afs|Ans|Ao|Aos|Aprk|Aprn|Aps|Ars|As|Asz|Azs|Komp|Konf|Kse|Kseo|Kss|Ksz|Na|Nad|Nao|Ncn|Nk|Ntn|Obn|Plen|Plsn|Pst|Rozk|Rs|S|Spr|Sst|Vol)$')])),
                ('number', models.PositiveIntegerField()),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1990)])),
                ('auxid', models.IntegerField(default=0)),
                ('desc', models.CharField(blank=True, max_length=255)),
                ('hash', models.CharField(blank=True, max_length=32, validators=[django.core.validators.RegexValidator(regex='[0-9a-f]{32}')])),
                ('subhash', models.CharField(blank=True, max_length=32, validators=[django.core.validators.RegexValidator(regex='[0-9a-f]{32}')])),
                ('changed', models.DateTimeField(null=True)),
                ('updated', models.DateTimeField(null=True)),
                ('notify', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='szr.Court')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
