# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('szr', '0002_remove_proceedings_subhash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proceedings',
            name='updated',
            field=models.DateTimeField(db_index=True, null=True),
        ),
    ]
