# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2016-07-11 18:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('szr', '0003_auto_20160628_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='court',
            name='reports',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='szr.Court'),
        ),
    ]
