# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2016-07-13 02:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('szr', '0004_auto_20160711_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='court',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
