# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 12:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('szr', '0006_auto_20161007_1459'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='proceedings',
            unique_together=set([]),
        ),
    ]
