#!/bin/bash

remote='legal.pecina.cz'
user='legal'
opts='-vrlpthHzxc --delete'
files='legal collect fonts activate manage.py requirements.txt sphinx.conf log patches scripts'
basedir='/home/legal'
scriptpath='./scripts'

"$scriptpath"/make-static

rsync $opts --exclude-from=- $files $user@$remote:$basedir/ <<EOF || exit
.*
*.pyc
*.log
*.log.*
*~
*.po
secrets.py
static/
/backup/
/repo/
__pycache__/
'#*'
EOF

if [ -e secrets.py ]; then
    rsync $opts secrets.py $user@$remote:$basedir/legal/ || exit
fi

ssh $user@$remote 'source activate && pip install -U pip && pip install -r requirements.txt && scripts/apply-patches' || exit

ssh $user@$remote 'touch legal/wsgi.py' || exit

echo 'Success'
