#!/bin/bash

apps='cin cnb common dvt hjp hsp knr lht psj sop szr sur udn sir dir pir kos'

par='--update --style=compressed -I legal/common/static'

for b in $apps; do
    sass $par legal/$b/static/$b.scss:legal/$b/static/$b.css || exit
done
sass $par legal/common/static/acc.scss:legal/common/static/acc.css || exit
