#!/bin/bash

scriptpath='./scripts'

"$scriptpath"/dosass || exit
./manage.py collectstatic --noinput --ignore='*.scss' --ignore='*.map' || exit
"$scriptpath"/douglifyjs || exit
cp -r external/* collect || exit
mkdir -p collect/fonts
cp fonts/* collect/fonts || exit
