#!/bin/bash

scriptpath='./scripts'

"$scriptpath"/dosass || exit
./manage.py collectstatic --noinput --ignore='*.scss' --ignore='*.map' || exit
"$scriptpath"/douglifyjs || exit
cp external/* collect || exit
cp fonts/* collect/fonts || exit
