# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-07 14:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('knr', '0004_auto_20160726_0137'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='car',
            unique_together=set([('abbr', 'uid')]),
        ),
        migrations.AlterUniqueTogether(
            name='formula',
            unique_together=set([('abbr', 'uid')]),
        ),
        migrations.AlterUniqueTogether(
            name='place',
            unique_together=set([('abbr', 'uid')]),
        ),
    ]
