# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-12 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knr', '0007_auto_20161218_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='abbr',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='formula',
            name='abbr',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='place',
            name='abbr',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='rate',
            name='fuel',
            field=models.CharField(max_length=150),
        ),
    ]
