# Generated by Django 2.1.7 on 2019-02-23 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knr', '0008_auto_20170812_0822'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='cons3',
            new_name='cons',
        ),
    ]
