# Generated by Django 2.1.7 on 2019-02-23 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knr', '0009_auto_20190223_1001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='cons1',
        ),
        migrations.RemoveField(
            model_name='car',
            name='cons2',
        ),
    ]
