# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 13:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pwresetlink',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='pwresetlink',
            name='timestamp_add',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
