# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_lock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pending',
            name='timestamp_add',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
