# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-12 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_auto_20170725_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lock',
            name='name',
            field=models.CharField(max_length=150, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pending',
            name='lock',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='pending',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='preset',
            name='name',
            field=models.CharField(db_index=True, max_length=150, unique_for_date='valid'),
        ),
    ]
