# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 16:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_auto_20170820_0520'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='timestamp_add',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cache',
            name='timestamp_add',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
