# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_auto_20170820_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cache',
            name='url',
            field=models.URLField(unique=True),
        ),
    ]
