# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_auto_20170820_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='timestamp_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='timestamp_add',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='cache',
            name='timestamp_add',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
