# Generated by Django 2.0.6 on 2018-06-14 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_auto_20170820_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=32)),
                ('filename', models.CharField(max_length=255)),
                ('url', models.URLField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='doc',
            unique_together={('app', 'filename')},
        ),
    ]
