# Generated by Django 2.1.7 on 2019-02-23 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_auto_20180614_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cache',
            name='url',
            field=models.URLField(max_length=255, unique=True),
        ),
    ]
