# -*- coding: utf-8 -*-
# Generated by Django 1.10rc1 on 2016-07-31 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psj', '0003_auto_20160730_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
