# -*- coding: utf-8 -*-
# Generated by Django 1.10rc1 on 2016-07-31 22:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psj', '0004_auto_20160731_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='courtroom',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='courtroom',
            name='name',
        ),
    ]
