# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-11 03:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psj', '0007_auto_20161007_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courtroom',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='hearing',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='judge',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='party',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
