# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psj', '0009_task_timestamp_add'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hearing',
            old_name='timestamp',
            new_name='timestamp_add',
        ),
        migrations.RenameField(
            model_name='party',
            old_name='timestamp',
            new_name='timestamp_add',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='timestamp',
            new_name='timestamp_update',
        ),
        migrations.AddField(
            model_name='hearing',
            name='timestamp_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='party',
            name='timestamp_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
